### ISSUE TITLE
style issue in Walker for WP 4.5

### ISSUE THREAD

**Issue by mralessio** [helgatheviking/Nav-Menu-Roles#17]
Hi! Found some issue with a style when category tab is opened in Menu Structure (please see screenshot) Wordpress 4.5.1
Can be corrected by adding 'overflow:hidden' on <div class="menu-item-settings">
![wordpress](https://cloud.githubusercontent.com/assets/16015111/14997553/4c290826-1190-11e6-88ff-41f469c64d9e.png)

**Comment by helgatheviking** [comment]
Could you both test the [wp-4.5-compat](https://github.com/helgatheviking/Nav-Menu-Roles/tree/wp-4.5-compat) branch?

**Comment by grappler** [comment]
Works for me :smile:

**Comment by helgatheviking** [comment]
Great, thanks for checking. I just wanted a second pair of eyes. I'll try to get it packaged up for the SVN repo. (I hate SVN)
