### ISSUE TITLE
Update Walker for WP 4.5

### ISSUE THREAD

**Issue by grappler** [helgatheviking/Nav-Menu-Roles#19]
In WP 4.5 the menu items looks like this because the class ` wp-clearfix` is missing.

![image](https://cloud.githubusercontent.com/assets/1785641/15013419/c3f9ea0e-11ff-11e6-9bfd-c564f72e66db.png)

**Comment by lkraav** [comment]
This is real, I'm seeing the same thing.

**Comment by helgatheviking** [comment]
Duplicate of #17

**Comment by helgatheviking** [comment]
Could you both test the [wp-4.5-compat](https://github.com/helgatheviking/Nav-Menu-Roles/tree/wp-4.5-compat) branch?

**Comment by helgatheviking** [comment]
Fixed by 344988bc7d15120cbcdf0a6ce87c90df9f7e7b31
