### ISSUE TITLE
Version 1.8.6 breaks Admin functionality on child pages in WP 4.6.1

### ISSUE THREAD

**Issue by conovercompany** [helgatheviking/Nav-Menu-Roles#22]
I updated to the newest plugin and it broke the admin functionality of my child pages.  The interface only partially loads on child pages.  It stops loading when it gets to the page attributes.  Even the screen options and help tabs do not work.  Slide out menus from the admin bar on the left (forms, appearance, plugins, etc) do not work either.

![12-9-2016 12-37-50 pm](https://cloud.githubusercontent.com/assets/669681/21060421/e6a3c0a2-be0c-11e6-9f94-d02cb96b9055.png)

The interface loads just fine on parent pages.

![12-9-2016 12-44-04 pm](https://cloud.githubusercontent.com/assets/669681/21060472/320dabde-be0d-11e6-8e07-9a0b3775639c.png)

Only way to get the pages to load correctly is to disable and delete the plugin.  Disabling the plugin does not work.  You must actually remove from the site.  I tried bring back version 1.8.3 from another site where it still works and the problem persists.  I am running WP 4.6.1

**Comment by helgatheviking** [comment]
NMR only effects the appearance>menu page and should have zero effect on the edit page screens. I would suggest you enable [`WP_DEBUG`](https://codex.wordpress.org/WP_DEBUG) and `WP_DEBUG_LOG` so you can get a better sense of what is causing your issue.
