### ISSUE TITLE
Show/Hide whole menus

### ISSUE THREAD

**Issue by lkraav** [helgatheviking/Nav-Menu-Roles#26]
Turns out I have a use case right now, where we could deploy an admin-only visible menu live where people could work on it for some time, then we publish when we're ready with it. Menus don't seem to have Draft etc statuses.

It doesn't look like this is currently implemented. Could be part of the Menu Settings sections.
![screenshot from 2017-07-21 16-45-00](https://user-images.githubusercontent.com/147228/28466135-01320b36-6e34-11e7-99fd-6da7ac4e34fb.png)

Any reasons why not? @helgatheviking are you open to a PR for this?

**Comment by helgatheviking** [comment]
I'm very hesitant to add totally new functionality to this plugin. How big of a PR are we talking about? Might it not be better to create a plugin that adds a Draft status to menus?

**Comment by lkraav** [comment]
I don't know either way yet... just seemed like a natural fit here. I'll look into what's needed in a bit more detail and report back.
