### ISSUE TITLE
New release not working with WP 4.8.3

### ISSUE THREAD

**Issue by jurekure** [helgatheviking/Nav-Menu-Roles#29]
After last update of plugin, my page doesn't load anymore?
I have solved the issue with going to previous release (1.8) but would be nice to have latest release?
Any suggestions?

**Comment by helgatheviking** [comment]
"my page" = which page? I can't reproduce any errors against WP 4.8.3 and I'm pretty sure nothing major has changed between 4.8.2 and 4.8.3. I recommend the standard debug protocol, test against a default theme and disable other plugins, then re-enable them one at a time.
