### ISSUE TITLE
Page Menus not showing for everyone but Custom Links do

### ISSUE THREAD

**Issue by Elxafil** [helgatheviking/Nav-Menu-Roles#30]
So not sure how this happened but for some reason the front page of my site has now got problems and is not showing the menu items properly, is this perhaps an issue with 4.9? I have attached below a screenshot of 2 menu items in which both items are displayed publicly whether or not they are logged in however the custom link is the only one which shows for everyone whether or not they are logged in and the page menu does not.
Here is an example: http://prntscr.com/j087vn

You can see the menu at: http://www.blockode.net

**Comment by helgatheviking** [comment]
Hi Elxafil. Could you step through a debug process of switching to a default theme and disabling plugins one at a time? You can use [WP Staging](https://wordpress.org/plugins/wp-staging/) to set up a staging site and avoid doing this on your live site. It's important to know whether you have any conflicts that are causing this problem.

**Comment by Elxafil** [comment]
@helgatheviking just done all that and still no difference, the menus work fine for specific roles when logged in it's just none work when users are logged out and I want them to be displayed for everyone.

**Comment by helgatheviking** [comment]
If you send admin creds to your staging site, I will take a look when I can
https://www.kathyisawesome.com/contact/
