### ISSUE TITLE
Wordpress Version 4.9.5

### ISSUE THREAD

**Issue by TomWilli** [helgatheviking/Nav-Menu-Roles#31]
Doesnt work with WP 4.9.5

**Comment by RichardCoffee** [comment]
I have it running on several sites using 4.9.5, and am having no problem with it.  What sort of issues are you having?

**Comment by helgatheviking** [comment]
@TomWilli Have you reviewed the [FAQ](https://github.com/helgatheviking/Nav-Menu-Roles#i-dont-see-the-nav-menu-roles-options-in-the-admin-menu-items)? "Doesn't work" is vague, but "doesn't work" in the admin is the result of a conflict with either your theme or another plugin. "Doesn't work" on the front-end, is usually a caching problem.

**Comment by TomWilli** [comment]
Ok thanks. 
I have reinstalled the plugin now it works
