### ISSUE TITLE
Nav Menu Roles - Sub-menu Items do not show after convert to HTTPS

### ISSUE THREAD

**Issue by jcooksey84** [helgatheviking/Nav-Menu-Roles#32]
Hello,

I converted out website from HTTP to HTTPS. Out nav menu will only work for main category items. Unfortunately, any sub-menu items attached to a main category will not display via drop-down. Please advise. Please note, I had to revert to HTTP to allow our visitors access to the full website.

**Comment by helgatheviking** [comment]
Sorry, I don't know what to suggest here. NMR *only* checks user roles. You may have caching or other server related things causing problems.
