### ISSUE TITLE
Remove .role-input-holder `width` and `float` style

### ISSUE THREAD

**Issue by lkraav** [helgatheviking/Nav-Menu-Roles#36]
It turns out that with tens of membership plans (we sell online trainings), this width-restricted floating makes the menu editor role checkbox list an incomprehensible mess.

100% wide rows are significantly saner to work with:

![image](https://user-images.githubusercontent.com/147228/65686713-6eb6aa00-e06e-11e9-90a6-15e065d42d03.png)

https://github.com/helgatheviking/Nav-Menu-Roles/blob/master/nav-menu-roles.php#L348 could be `<div class="role-input-holder" style="margin: 2px 0;">`

Your thoughts?

**Comment by helgatheviking** [comment]
This doesn't sound like a bad idea! Want to send a PR? If you wait a few days you could count it towards your [Hacktoberfest](https://hacktoberfest.digitalocean.com/) efforts. :)
