### ISSUE TITLE
not fully working with 5.3.2

### ISSUE THREAD

**Issue by zigipha** [helgatheviking/Nav-Menu-Roles#39]
With 5.3.2 (maybe earlier?), when i select display “logged in users”, i don’t get teh list of user roles to select from. I have tried selecting all users and then back to logged in users, and still dont get the options to select roles.

Thoughts?

**Comment by helgatheviking** [comment]
Are there any errors in the developer console? Can you reproduce this with only NMR active?

**Comment by zigipha** [comment]
I am a bit of a novice..how do I access developer console and what is nmr?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by helgatheviking** [comment]
NMR is the plugin, Nav Menu Roles.

In Firefox you can get to the console by pressing CTRL+SHIFT+K
Or in Chrome, here's some info about their console https://developers.google.com/web/tools/chrome-devtools/javascript

**Comment by zigipha** [comment]
So you mean disable all  other plugins and leaving only nmr running? I’ll have to try during a test window…

**Comment by helgatheviking** [comment]
Yes. You can use [WP Staging](https://wordpress.org/plugins/wp-staging/) to set up a test site.
