### ISSUE TITLE
Sort roles alphabetically

### ISSUE THREAD

**Issue by lkraav** [helgatheviking/Nav-Menu-Roles#54]
As shown in https://github.com/helgatheviking/Nav-Menu-Roles/issues/36#issue-498841559 opening screenshot, things can get out of hand quickly with a large role list. Really difficult to find anything without Ctrl+F help.

Any objections? I can file what I think will be a pretty simple PR.

**Comment by helgatheviking** [comment]
No objections. That works for me. Can it also alphabetize the roles in the customizer? one day, do you think something like Select2 would ever make sense... or is it overkill?

**Comment by lkraav** [comment]
> one day, do you think something like Select2 would ever make sense... or is it overkill?

I've been considering multi-select UX issues recently. Thoughts

:heavy_plus_sign: final result displayed in minimal screen real estate
:heavy_minus_sign: inline search sometimes doesn't display enough information, you can't tell if you're selecting the right thing (issue with posts/pages, could be 10 items with very similar titles, which one do you pick - usually nobody displays slugs)
:heavy_minus_sign: seeing full list may be useful for finding mistakes - inline search puts user in "you don't know what you don't know" scenario

Max-height scrollable option list is sometimes useful.

Filterable full option list display sounds nice, in theory.

So yeah, not sure.

**Comment by helgatheviking** [comment]
Sounds like a problem for another day then :) let's just stick to alphabetical ordering for now.

**Comment by helgatheviking** [comment]
>inline search sometimes doesn't display enough information, you can't tell if you're selecting the right thing (issue with posts/pages, could be 10 items with very similar titles, which one do you pick - usually nobody displays slugs) 

is this a problem for roles? Are they likely to be as long as post titles?

>seeing full list may be useful for finding mistakes - inline search puts user in "you don't know what you don't know" scenario

select2/selectWoo (the latter fork supposedly has some accessibility enhancements over the former) allows you to display a dropdown with all the options, while still maintaining search functionality. I built this for something else the other day:

![Screen Recording 2020-09-26 at 11 17 10 47 AM](https://user-images.githubusercontent.com/507025/94346515-57e0c580-ffea-11ea-9993-bdd03b2ee28c.gif)

no idea if I could make that work in the Customizer though... phew.

**Comment by lkraav** [comment]
> > inline search sometimes doesn't display enough information, you can't tell if you're selecting the right thing (issue with posts/pages, could be 10 items with very similar titles, which one do you pick - usually nobody displays slugs)
> 
> is this a problem for roles? Are they likely to be as long as post titles?

In the case of Memberships Plans integrations, yes.

![image](https://user-images.githubusercontent.com/147228/65686713-6eb6aa00-e06e-11e9-90a6-15e065d42d03.png)

> > seeing full list may be useful for finding mistakes - inline search puts user in "you don't know what you don't know" scenario
> 
> select2/selectWoo (the latter fork supposedly has some accessibility enhancements over the former) allows you to display a dropdown with all the options, while still maintaining search functionality. I built this for something else the other day:

In use case I'm referring to, you need another dimension (post slug) often enough, to tell the difference between 2 or more similarly named posts. For your screencast, imagine 3 different elements named "Week" - with single dimension (title only), how will you choose?

**Comment by helgatheviking** [comment]
@Ikraav will 6486497 do it for you?

**Comment by lkraav** [comment]
Lgtm tyvm :+1:
