### ISSUE TITLE
Headers already sent

### ISSUE THREAD

**Issue by helgatheviking** [helgatheviking/Nav-Menu-Roles#57]
> Warning: Cannot modify header information – headers already sent by (output started at /home/bacchi5/public_html/massnew2/wp—content/plugins/nav—menu—roles/inc/customizer.php:164) in /home/bacchi5/public_html/massnew2/wp-includes/funclions.php at line 6352
> 
> Warning: Cannot modify header information – headers already sent by (output started at /home/bacchi5/public_html/massnew2/wp—content/plugins/nav—menu—roles/inc/customizer.php:164) in /home/bacchi5/public_html/massnew2/wp-admin/includes/misc.php line1310
> 
> Warning: Cannot modify header information – headers already sent by (output started at /home/bacchi5/public_html/massnew2/wp—content/plugins/nav—menu—roles/inc/customizer.php:164) in /home/bacchi5/public_html/massnew2/wp-admin/customize.php at line 126

[Line 164](https://github.com/helgatheviking/Nav-Menu-Roles/blob/master/inc/customizer.php#L164) appears to be 
```
if ( $wp_customize->settings_previewed() ) {
```

Not really sure why that would throw the headers already sent notice.

**Comment by bmcculley** [comment]
Is this still an issue? I don't seem to be able to reproduce this.

**Comment by helgatheviking** [comment]
Me neither... it's probably safe to close at this point
