### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by szepeviktor** [helgatheviking/Nav-Menu-Roles#62]
./phpcs.xml:23: simultanously ==> simultaneously
./readme.md:98: willl ==> will
./readme.md:132: reenable ==> re-enable
./readme.md:176: visibilty ==> visibility
./readme.txt:98: willl ==> will
./readme.txt:133: reenable ==> re-enable
./readme.txt:177: visibilty ==> visibility
./readme.txt:326: hypenated ==> hyphenated
./inc/class-walker-nav-menu-edit-roles.php:3: Modifed ==> Modified
./inc/class-walker-nav-menu-edit-roles-4.5.php:6: Modifed ==> Modified
./inc/class-nav-menu-roles-import.php:191: verion ==> version

Codespell told me all this.

**Comment by helgatheviking** [comment]
Thanks! Should be fixed now, though will need another tag bump to get deployed to wp.org (not sure I can fix up my deploy process anyway)

**Comment by szepeviktor** [comment]
You're welcome.
