### ISSUE TITLE
What WordPress and PHP Versions Supported

### ISSUE THREAD

**Issue by nonuniverse** [helgatheviking/Nav-Menu-Roles#66]
Hello, I am on WordPress 6.1.1. It looks like this plugin has not been tested with this version.

Also, what is the highest PHP version supported by your plugin? I need PHP 8.0+ in order for my other plugins to work properly.

Best Regards, NonUniverse

**Comment by helgatheviking** [comment]
There's not a ton of change in the menu area between 6.1 and 6.0, so I would expect it to still be fine. But I rely on the community to report bugs as this is a free plugin and I can't test it extensively on every update. But let's say that I haven't gotten any recent reports of PHP 8 compatibility errors so I suspect it's ok with 8 and 8.1.... 8.2 is more recent and not many hosts are running it yet so would feel less confident about that until somebody tests it. WordPress itself isn't even fully 8.2 ready as far as I know.

So my recommendation would be to create a staging site with PHP 8.1/2 and WP 6.2 and test it out. It will be a big help to me if you can report any issues you uncover with NMR.. as it will be a lot easier for me to try to update it with something specific in mind.

**Comment by nonuniverse** [comment]
Hello,

 

I was able to find the SMOKE REPORT for Nav Menu Roles. Someone tested it on WordPress 6.1.1. and PHP 8.1.12. Here’s the link. This may make it easier to answer this question in the future: https://plugintests.com/plugins/wporg/nav-menu-roles/latest

 

Best Regards, Dianne

**Comment by helgatheviking** [comment]
Thanks, hadn't heard of that site and not really clear exactly what they test, but that matches with what I have seen come through in support questions.
