### ISSUE TITLE
Nav Menu Roles plugin no longer doing what it should

### ISSUE THREAD

**Issue by GenPPI** [helgatheviking/Nav-Menu-Roles#68]
Hi there I've been using this plugin for a few years with success. I have different membership levels and need them to see different menu options. 

Now it's stopped working, as in when I set up a menu item to be only visible to a certain role user, it's not working, I can only choose for it to be visible to all logged in or all logged out users. My website is www.peacefulparent.com 

Can anyone please help?

**Comment by helgatheviking** [comment]
Hi @GenPPI are you able to provide some steps I can follow to reproduce the issue? 

This plugin has not had any significant structural changes in years. Certainly nothing that would cause it to _stop_ working. It's more likely that something has changed at your site... is the theme different? Did your membership plugin change? either switched to a new plugin OR their codebase changed? 

This plugin relies on WordPress' built-in global _roles_ and I have seen multiple membership plugins that do NOT the built-in roles. I have built out a couple "bridge" plugins ([WooCommerce Memberships](https://github.com/helgatheviking/nav-menu-roles-woocommerce-memberships)) and ([Wishlist Members](https://github.com/helgatheviking/nav-menu-roles-wishlists-memberships)) but admittedly I have not tested those in years. 

NMR is extensible, so it would be possible to follow the template for those plugins to integrate with other membership plugins.

**Comment by GenPPI** [comment]
Thank you so much Kathy for getting back to me. Yes we changed from
S2Member to Membermouse a while ago and so possibly we've had the issue
since then since we were only really seeing the admin view and not checking
the view from the different member's view.

Let me think about this and get back to you but you've given me some clues
to investigate.
Genevieve


[image: photograph]

Genevieve Simperingham

Director & Co-Founder |
The Peaceful Parent Institute
Dip. Psychosynthesis Counselling,
Parent Educator, Instructor, Writer, Public Speaker and last but not least,
Mother
*p:* (027) 417-9198
*e:* ***@***.***
www.peacefulparent.com
[image: facebook icon]
<https://www.facebook.com/TheWayOfThePeacefulParent> [image:
linkedin icon]
<https://www.linkedin.com/in/genevieve-simperingham-05260424/> [image:
instagram icon] <https://www.instagram.com/peacefulparentinstitute/>

**Comment by helgatheviking** [comment]
Closing as stale. Please re-open if there's actually a bug in NMR.
