### ISSUE TITLE
Archive widget cannor be blocked

### ISSUE THREAD

**Issue by rh4789** [helgatheviking/Nav-Menu-Roles#9]
When I try to block the archives widget from pages (dropdown) I get it in list form plus I get the search widget, which I have already blocked separately.

When I unblock the search widget, the archives are blocked as supposed.

Thanks Kathy. Great plugin. Rick

**Comment by helgatheviking** [comment]
You can't block widgets with NMR, it only deals with menu items.

**Comment by rh4789** [comment]
Is this the plugin that hides/shows widgets? 

"Show Widget for:"  everyone, etc?

That is what I mean.

**Comment by rh4789** [comment]
OK, maybe I am looking at the wrong place. Sorry.

**Comment by helgatheviking** [comment]
No, none of my plugins do that. Sounds like you are looking for Widget Logic, or something similar. Go to your dashboard and see which plugins you have so you can find the right place to get help.
